name: deploy-static-website-in-s3 # custom name
on: 
  push:
    branches: 
      - main
jobs:
  sync: # custom name
    runs-on: ubuntu-latest
    steps: 
        - name: check-repo
          uses: actions/checkout@v3

        - name: configure-aws
          uses: aws-actions/configure-aws-credentials@v2
          with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ap-northeast-2  # Change this to your region of your bucket

        - name: Sync to S3
          run: aws s3 sync . s3://my-static-site-95678
        
    
